### ISSUE TITLE
build system explanation

### ISSUE THREAD

**Issue by jessicajonesunitedkingdom** [emoon/HippoPlayer#107]
hi

Is it possible to explain how exactly you compile so much code including libraries etc without using visual studio project files?
It's sounds insane to me or do you use a 3rd party build system I have never heard of?

**Comment by emoon** [comment]
Most cross-platform systems doesn't use VS project files because you can only compile them on Windows (and my primary OS is Linux these days)

There are many, many ways to compile code in a cross-platform way where https://cmake.org is one of the more popular these days. I personally prefer using Tundra to compile the code as I like the way how you configure the build steps better.

You can read more about it in the doc here https://github.com/deplinenoise/tundra/blob/master/doc/manual.asciidoc

**Comment by jessicajonesunitedkingdom** [comment]
ok I was very new to this and now understand!
I closed this.
